### ISSUE TITLE
Install from HACS not working "Unknown error occurred"

### ISSUE THREAD

**Issue by mchooha** [jugla/worldtidesinfocustom#13]
Hi,

I have installed the "worldtidesinfocustom" integrations from HACS.
The proceed to the Config, Integrations, click "Add Integration", find "World Tide Info Custom".
It then opens a dialog box. When I select either option (standard / expert), I receive in red " Unknown error occurred" and cannot proceed to setup.

![image](https://user-images.githubusercontent.com/59675464/134601958-3367f47f-a5ea-418b-8f3a-c96494612702.png)

My setup is running:
core-2021.9.7
supervisor-2021.09.0
and latest HACS version: 1.15.2

When I look at the log viewer it is reporting the following:

  File "/config/custom_components/worldtidesinfocustom/config_flow.py", line 102, in config_expert_schema
    if async_get_used_api_key(self.hass) == None:
  File "/config/custom_components/worldtidesinfocustom/__init__.py", line 78, in async_get_used_api_key
    for entry_id, coordinator in hass.data[DOMAIN][DATA_COORDINATOR].items():
KeyError: 'worldtidesinfocustom'
  File "/config/custom_components/worldtidesinfocustom/config_flow.py", line 73, in config_standard_schema
    if async_get_used_api_key(self.hass) == None:
  File "/config/custom_components/worldtidesinfocustom/__init__.py", line 78, in async_get_used_api_key
    for entry_id, coordinator in hass.data[DOMAIN][DATA_COORDINATOR].items():
KeyError: 'worldtidesinfocustom'
  File "/config/custom_components/worldtidesinfocustom/config_flow.py", line 73, in config_standard_schema
    if async_get_used_api_key(self.hass) == None:
  File "/config/custom_components/worldtidesinfocustom/__init__.py", line 78, in async_get_used_api_key
    for entry_id, coordinator in hass.data[DOMAIN][DATA_COORDINATOR].items():
KeyError: 'worldtidesinfocustom'
  File "/config/custom_components/worldtidesinfocustom/config_flow.py", line 73, in config_standard_schema
    if async_get_used_api_key(self.hass) == None:
  File "/config/custom_components/worldtidesinfocustom/__init__.py", line 78, in async_get_used_api_key
    for entry_id, coordinator in hass.data[DOMAIN][DATA_COORDINATOR].items():
KeyError: 'worldtidesinfocustom'

My interpretation of this is that is is talking about a Key error/ api key, however because of the error that stops me proceeding with the integration setup, i cannot add my API key to solve it. 

Appreciate any assistance here.

Thank you

**Comment by jugla** [comment]
Hello,
Please, can you tell me if you have enter a name for this location or you use the default one ?
(In which mode you have declared your location : expert definition or standard ?)
I wonder why you have 

> KeyError: 'worldtidesinfocustom'

**Comment by mchooha** [comment]
Hi mate,

I have not got to any area where I can name a location. 

Am I right in understanding, all I need to do is install the the HACS integration and then setup the integration in UI (i.e. no config.yaml entries) ??

https://user-images.githubusercontent.com/59675464/134648317-1f2903f4-b03e-4dd2-8a89-6a683270fb4b.mp4

Does that help explain at all??

Thank you

**Comment by jugla** [comment]
Thanks for the video, nothing is expected in configuration.yaml.
I will see this week end. 
As a work around, you can write in configuration.yaml (depricated method)

**Comment by jugla** [comment]
Please can tell me if you select first "expert definition" , if it's ok?

**Comment by mchooha** [comment]
Thanks @jugla.

Tried selecting expert first and was same unsuccessful result.

https://user-images.githubusercontent.com/59675464/134674000-8530ec85-2f00-4592-aa60-a17ee30c3dcd.mp4

Log Viewer:
    if async_get_used_api_key(self.hass) == None:
  File "/config/custom_components/worldtidesinfocustom/__init__.py", line 78, in async_get_used_api_key
    for entry_id, coordinator in hass.data[DOMAIN][DATA_COORDINATOR].items():
KeyError: 'worldtidesinfocustom'

I'm OK to sit tight if your going to look at this over the weekend to validate a fix if that helps rather than implement the manual method. Let me know if I can help anymore. 

Thanks.

**Comment by jugla** [comment]
Hello,
I will look this week end for a patch.

**Comment by jugla** [comment]
Hello
I've changed the initialization in config flow.
Please can you try the v5.3.1.
Thanks in advance
Philippe

**Comment by mchooha** [comment]
Hi @jugla ,
Thanks mate.
Have updated to v5.3.1 and reattempted with both Standard and Expert and receive the same error.

Here is what it seems to be dumping when I select a type of config (either standard or expert):

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/worldtidesinfocustom/config_flow.py", line 224, in async_step_user
    return await self.async_step_config_def_expert()
  File "/config/custom_components/worldtidesinfocustom/config_flow.py", line 205, in async_step_config_def_expert
    new_schema = self.config_expert_schema()
  File "/config/custom_components/worldtidesinfocustom/config_flow.py", line 102, in config_expert_schema
    if async_get_used_api_key(self.hass) == None:
  File "/config/custom_components/worldtidesinfocustom/__init__.py", line 78, in async_get_used_api_key
    for entry_id, coordinator in hass.data[DOMAIN][DATA_COORDINATOR].items():
KeyError: 'worldtidesinfocustom'
`
Have replicated a number of times and it is the same logging being entered.

Thanks.

**Comment by jugla** [comment]
I've created v5.3.2, tell me

**Comment by mchooha** [comment]
Hi @jugla 
You have fixed it. Thank you for your integration and responsiveness.

https://user-images.githubusercontent.com/59675464/134787529-0ee27c4f-9353-44ec-bf9c-b6fe0f4a41f2.mp4

love your work.

**Comment by jugla** [comment]
Thanks for your message :-)
