### ISSUE TITLE
Plot and Long Plot do not load

### ISSUE THREAD

**Issue by billg118** [jugla/worldtidesinfocustom#31]
I'm running in Docker and installed this through HACS

The integration works fine except for the plot and long plot. All entities show correct values except for those. The curve picture also works fine.

I see these line in my HA log:
```
[custom_components.worldtidesinfo.custom.camera] Could not read camera [redacted] image from file: /config/www                                                                                                           /[redacted]_plot_long.png

[custom_components.worldtidesinfocustom.camera] Could not read camera [redacted] image from file: /config/www/[redacted]_plot.png
```
I looked in the folder and those files do not exist.

On startup it looks like it fails to create the images.

```
[custom_components.worldtidesinfocustom.camera] Camera: Sync Fetch new picture image from /config/www/[redacted]_plot.png
[custom_components.worldtidesinfocustom.camera] Could not read camera Portsmouth, NH image from file: /config/www/[redacted]_plot.png
[custom_components.worldtidesinfocustom.camera] Camera update :  /config/www/[redacted]_plot.png
[custom_components.worldtidesinfocustom.camera] Camera Async Update [redacted]
[custom_components.worldtidesinfocustom.camera] Camera: Sync Fetch new picture image from /config/www/[redacted]_plot_long.png
[custom_components.worldtidesinfocustom.camera] Could not read camera [redacted] image from file: /config/www/[redacted]_plot_long.png
[custom_components.worldtidesinfocustom.camera] Camera update :  /config/www/[redacted]_plot_long.png
```

I also see these two warnings in the logs. I do not know if they're related or not.

```
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'worldtidesinfocustom' calls async_forward_entry_setup for integration, worldtidesinfocustom with title: World Tides Info Custom Cloud API ([redacted_lat_long]) and entry_id: 01J2RZR9NRD4MY0FDYR465D5GY, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/worldtidesinfocustom/__init__.py, line 180: hass.async_create_task(, please create a bug report at https://github.com/jugla/worldtidesinfocustom/issues


WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/.storage/worldtidesinfocustom.[redacted].ser', 'rb') inside the event loop by custom integration 'worldtidesinfocustom' at custom_components/worldtidesinfocustom/storage_mngt.py, line 81: file_handler = open(self._storage_full_path, "rb") (offender: /config/custom_components/worldtidesinfocustom/storage_mngt.py, line 81: file_handler = open(self._storage_full_path, "rb")), please create a bug report at https://github.com/jugla/worldtidesinfocustom/issues
```

**Comment by paxanga** [comment]
Same issue here

**Comment by armandkd** [comment]
Same issue...

**Comment by pedromrg** [comment]
Same here, following

**Comment by KjellRanda** [comment]
Also get this error. HA 2024.10.2 running in a container on a RPI 4.

**Comment by KjellRanda** [comment]
And if I click on any of the 3 plots the following is logged:


2024-10-20 16:12:29.626 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 813, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 853, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 673, in handle_async_mjpeg_stream
    return await self.handle_async_still_stream(request, self.frame_interval)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 661, in handle_async_still_stream
    return await async_get_still_stream(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 294, in async_get_still_stream
    img_bytes = await image_cb()
                      ^^^^^^^^^^
TypeError: TidesPicture_FromFile.async_camera_image() missing 2 required positional arguments: 'width' and 'height'

**Comment by nigelnason** [comment]
Any updates on this issue
Been happening to me since I first installed it nearly a year ago
